# Generated by Django 2.1.7 on 2019-03-12 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brightness', models.PositiveSmallIntegerField(blank=True, default=50)),
                ('brightnessMode', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('delayBetweenColumns', models.PositiveSmallIntegerField(blank=True, default=100)),
                ('currentImage', models.CharField(blank=True, max_length=40)),
                ('motorSpeed', models.PositiveSmallIntegerField(blank=True, default=50)),
                ('coldLedBrightness', models.PositiveSmallIntegerField(blank=True, default=50)),
                ('warmLedBrightness', models.PositiveSmallIntegerField(blank=True, default=50)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Lampbody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=20)),
                ('settings', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lampshade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=20)),
                ('settings', models.TextField(blank=True)),
                ('lampbody', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Lampbody')),
            ],
        ),
        migrations.AddField(
            model_name='lamp',
            name='lampshade',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Lampshade'),
        ),
    ]
