# Generated by Django 2.1.7 on 2019-03-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190312_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamp',
            name='divider',
            field=models.PositiveSmallIntegerField(blank=True, default=16),
        ),
    ]
