# Generated by Django 2.1.7 on 2019-05-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_lamp_divider'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamp',
            name='moveDelay',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='lamp',
            name='delayBetweenColumns',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
