# Generated by Django 2.1.7 on 2019-06-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190524_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamp',
            name='masterDelay',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='lamp',
            name='slaveDelay',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
