# Generated by Django 2.1.7 on 2019-06-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190602_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamp',
            name='Delay0M',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='lamp',
            name='Delay0S',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='lamp',
            name='Delay180M',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='lamp',
            name='Delay180S',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
