version: '3'

services:
  db:
    restart: always
    image: postgres
  web:
    restart: always
    build: .
    command: bash -c "service mosquitto start && python3 novella/manage.py runserver --insecure 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "1883:1883"
    depends_on:
      - db
